---
- name: MY AS3 PLAYBOOK
  hosts: localhost 
  connection: local
  gather_facts: no

  vars:
    uri_method: POST

  vars_files:
    - ../creds/big_creds.yaml

  tasks:

  - name: Create a A4
    uri:
      url: https://35.176.153.176/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','as3-declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: as3_response


  - name: DEBUG OUT AS3 RESPONSE
    debug:
      msg: "{{as3_response.json.declaration.arch.A4.serviceMain.virtualAddresses}}"
...



